import type { NextPage } from "next";

import Header from "components/Header";
import Screen from "components/Screen";
import Head from "next/head";
import Main from "components/Main";
import Footer from "components/Footer";

import { encodeUrlSprite } from "utils/hash";
import LZString from "utils/lz";
import { useEffect, useMemo, useState } from "react";
import Timeline from "components/Timeline";
import Editor from "components/Editor";
import guid from "utils/guid";
import Router, { useRouter } from "next/router";
import SpriteForm from "components/SpriteForm";

import { useSpriteStore } from "../../../../src/stores/useSpriteStore";
import { spriteRepository } from "../../../../src/repositories/SpriteRepository";
import { defaultColors } from "../../../../data/palettes";

const Home: NextPage = () => {
  const { query, push } = useRouter();
  const {
    currentSprite,
    loadSprite,
    clearFrame,
    currentFrame,
    setFrame,
    addFrame,
    deleteFrame,
  } = useSpriteStore();

  const spriteId = useMemo(() => {
    return query.spriteId ? String(query.spriteId) : undefined;
  }, [query.spriteId]);

  const showEditMode = useMemo(() => {
    return query.editMode === "true";
  }, [query.editMode]);

  useEffect(() => {
    const loadData = async () => {
      if (spriteId) {
        const sprite = await spriteRepository.load(spriteId);
        if (sprite) {
          loadSprite(sprite);
        }
      } else {
        // Create new sprite
        const newSpriteId = guid();
        const newSprite = {
          id: newSpriteId,
          version: "2.0",
          name: "Untitled",
          description: "New sprite",
          palette: defaultColors,
          size: 11,
          fps: 10,
          frames: ["a".repeat(11 * 11)],
        };

        await spriteRepository.save(newSprite);
        loadSprite(newSprite);

        // Update URL with new sprite id
        push(`/app/editor/sprite/${newSpriteId}`, undefined, {
          shallow: true,
        });
      }
    };

    loadData();
  }, [spriteId, loadSprite, push]);

  const onShare = () => {
    if (currentSprite) {
      const urlSprite = encodeUrlSprite(currentSprite);
      const params = JSON.stringify(urlSprite);
      const compressedParams = LZString.compressToEncodedURIComponent(params);

      window.open(`/app/share?d=${compressedParams}`, "_blank");
    }
  };

  return (
    <Screen scrolling>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/x-icon" id="favicon" />
      </Head>

      <Header
        title={currentSprite?.name || "New Sprite"}
        action={{
          text: "Edit",
          url: `/app/editor/sprite/${spriteId}?editMode=true`,
        }}
      />

      <Main padded>
        {showEditMode && currentSprite ? <SpriteForm /> : null}

        {!showEditMode && (
          <>
            <Editor />
            <Timeline />
          </>
        )}
      </Main>
      <Footer
        action={{
          text: "Share",
          url: "#",
          onClick: onShare,
        }}
        shortcuts={[
          {
            children: "←",
            label: "Previous",
            hotKeys: "left",
            disabled: currentFrame === 0,
            onToggle: () => setFrame(currentFrame - 1),
          },
          {
            children: "→",
            label: "Next",
            hotKeys: "right",
            disabled: currentSprite
              ? currentFrame === currentSprite.frames.length - 1
              : false,
            onToggle: () => setFrame(currentFrame + 1),
          },
          {
            children: "⌘ + A",
            label: "Add blank",
            hotKeys: "cmd+a",
            onToggle: () => currentSprite?.frames && addFrame(currentFrame),
          },
          {
            children: "⌘ + D",
            label: "Duplicate",
            hotKeys: "cmd+d",
            onToggle: () => {
              if (currentSprite?.frames) {
                addFrame(currentFrame, currentSprite.frames[currentFrame]);
              }
            },
          },
          {
            children: "⌘ + E",
            label: "Delete",
            hotKeys: "cmd+e",
            onToggle: () => currentSprite?.frames && deleteFrame(currentFrame),
          },
          {
            children: "C",
            label: "Clear",
            hotKeys: "c",
            onToggle: clearFrame,
          },
        ]}
      />
    </Screen>
  );
};

export default Home;
