import type { NextPage } from "next";

import Header from "components/Header";
import Screen from "components/Screen";
import Head from "next/head";
import Main from "components/Main";
import Footer from "components/Footer";
import { useEffect, useState } from "react";
import { getAll, remove, set } from "utils/localStorage";
import localStorageKeys from "constants/localStorageKeys";
import { LegacySprite, Sprite } from "types/sprite";
import { Spritesheet } from "types/sheet";
import { useRouter } from "next/router";
import SpriteGrid from "components/SpriteGrid";
import { encodeUrlSprite } from "utils/hash";

type Creation = (Sprite | Spritesheet) & { type: "sprite" | "sheet" };

const Home: NextPage = () => {
  const router = useRouter();
  const [creations, setCreations] = useState<Creation[]>([]);

  useEffect(() => {
    // Load sprites
    const spriteItems = getAll(localStorageKeys.SPRITE);
    const sprites = (spriteItems
      ?.map((item) => {
        try {
          const parsed = JSON.parse(item) as Sprite;
          return { ...parsed, type: "sprite" as const };
        } catch (e) {
          return null;
        }
      })
      .filter(Boolean) || []) as Creation[];

    // Load spritesheets
    const sheetItems = getAll(localStorageKeys.SPRITESHEET);
    const sheets = (sheetItems
      ?.map((item) => {
        try {
          const parsed = JSON.parse(item) as Spritesheet;
          return { ...parsed, type: "sheet" as const };
        } catch (e) {
          return null;
        }
      })
      .filter(Boolean) || []) as Creation[];

    // Combine and sort by name
    const allCreations = [...sprites, ...sheets].sort((a, b) =>
      a.name.localeCompare(b.name)
    );

    setCreations(allCreations);
  }, []);

  const handleView = (id: string, type: "sprite" | "sheet") => {
    if (type === "sprite") {
      router.push(`/app/editor/sprite/${id}`);
    } else {
      router.push(`/app/editor/sheet/${id}`);
    }
  };

  const handleShare = (id: string) => {
    const creation = creations.find((item) => item.id === id);
    if (creation && creation.type === "sprite") {
      const sprite = creation as Sprite & { type: "sprite" };
      const { n, a, s, d, p, f } = encodeUrlSprite(sprite);
      const params = `?n=${n}&a=${a}&s=${s}&d=${d}&p=${p}&f=${f}`;
      window.open(`/app/share${params}`, "_blank");
    }
  };

  const handleDelete = (id: string, type: "sprite" | "sheet") => {
    if (type === "sprite") {
      remove(`${localStorageKeys.SPRITE}-${id}`);
    } else {
      remove(`${localStorageKeys.SPRITESHEET}-${id}`);
    }
    setCreations(creations.filter((item) => item.id !== id));
  };

  return (
    <Screen scrolling>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/x-icon" id="favicon" />
      </Head>

      <Header
        title="My Creations"
        action={{
          text: "Edit",
          url: "/app/my-creations?edit=true",
        }}
      />

      <Main centered padded>
        <SpriteGrid
          creations={creations}
          onView={handleView}
          onShare={handleShare}
          onDelete={handleDelete}
        />
      </Main>
      <Footer
        shortcuts={[
          {
            children: "L",
            label: "Login",
            hotKeys: "l",
            onToggle: () => router.push("/app/login"),
          },
          {
            children: "⏎",
            label: "Draw",
            hotKeys: "enter",
            onToggle: () => router.push("/app/editor/sprite"),
          },
        ]}
        action={{ text: "Draw!", url: "/app/editor/sprite" }}
      />
    </Screen>
  );
};

export default Home;
