import type { NextPage } from "next";

import Header from "components/Header";
import Screen from "components/Screen";
import Head from "next/head";
import Main from "components/Main";
import Footer from "components/Footer";
import { useEffect, useState } from "react";
import { getAll, remove, set } from "utils/localStorage";
import localStorageKeys from "constants/localStorageKeys";
import { LegacySprite, Sprite } from "types/sprite";
import { useRouter } from "next/router";
import SpriteGrid from "components/SpriteGrid";

const Home: NextPage = () => {
  const router = useRouter();
  const [sprites, setSprites] = useState<Sprite[]>([]);
  const [legacySprites, setLegacySprites] = useState<Sprite[]>([]);

  useEffect(() => {
    const legacyItems = getAll(localStorageKeys.LEGACY_SPRITES);
    const legacySpritesUnprocessed = legacyItems?.map((item) =>
      JSON.parse(item)
    ) as LegacySprite[];

    if (legacySpritesUnprocessed) {
      const processed = legacySpritesUnprocessed.map((legacy) => {
        const sprite = {
          id: legacy.id,
          version: "2.0.0",
          name: legacy.name,
          description: legacy.description,
          palette: [
            legacy.frames?.[0].split(";")[0],
            ...legacy.frames?.[0].split(";")[1]?.split(","),
          ],
          size: legacy.size,
          fps: 10,
          frames: legacy.frames?.map((frame) =>
            frame
              .split(";")[2]
              ?.split("")
              ?.map((pixel) =>
                pixel === "0"
                  ? "a"
                  : String.fromCharCode(pixel.charCodeAt(0) + 1)
              )
              .join("")
          ),
        } as Sprite;

        // Store sprite in localstorage
        set(
          `${localStorageKeys.SPRITE}-${sprite?.id}`,
          JSON.stringify({
            ...sprite,
            frames: sprite.frames,
            palette: sprite.palette,
          })
        );

        // Delete old legacy sprite
        remove(`${localStorageKeys.LEGACY_SPRITES}-${sprite?.id}`);

        return sprite;
      });

      setLegacySprites(processed);
    }
  }, []);

  useEffect(() => {
    const items = getAll(localStorageKeys.SPRITE);
    const sprites = items?.map((item) => JSON.parse(item)) as Sprite[];

    if (sprites) {
      setSprites(sprites);
    }
  }, []);

  return (
    <Screen scrolling>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header
        title="My Creations"
        action={{
          text: "Edit",
          url: "/app/my-creations?edit=true",
        }}
      />

      <Main centered padded>
        <SpriteGrid sprites={sprites} />
      </Main>
      <Footer
        shortcuts={[
          {
            children: "L",
            label: "Login",
            hotKeys: "l",
            onToggle: () => router.push("/app/login"),
          },
          {
            children: "⏎",
            label: "Draw",
            hotKeys: "enter",
            onToggle: () => router.push("/app/editor"),
          },
        ]}
        action={{ text: "Draw!", url: "/app/editor" }}
      />
    </Screen>
  );
};

export default Home;
