import type { NextPage } from "next";

import Header from "components/Header";
import Screen from "components/Screen";
import Head from "next/head";
import Image from "next/image";
import Main from "components/Main";
import Footer from "components/Footer";

const SpritePlayerLarge = dynamic(
  () => import("components/SpritePlayerLarge"),
  {
    ssr: false,
  }
);

import { getRandomHash } from "utils/hash";
import dynamic from "next/dynamic";
import { useMemo } from "react";
import { useRouter } from "next/router";
import { Sprite } from "types/sprite";

const Home: NextPage = () => {
  const { query } = useRouter();

  const spriteData = {
    id: query.id,
    name: query.name,
    description: "This is an example sprite",
    size: 11,
    frames: query.frames ? String(query.frames)?.split("_") : [],
  } as Sprite;

  return (
    <Screen>
      <Head>
        <title>{query.name} - Miko</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header
        action={{
          text: "My creations",
          url: "/app/my-creations",
        }}
      />

      <Main centered>
        <div
          style={{
            width: "100%",
            maxWidth: "48rem",
          }}
        >
          <SpritePlayerLarge spriteData={spriteData} />
        </div>
      </Main>

      <Footer
        shortcuts={[
          { children: "⌘ + L", label: "Login" },
          { children: "⌘ + D", label: "Draw" },
        ]}
        action={{ text: "Let me try!", url: "/app/editor" }}
      />
    </Screen>
  );
};

export default Home;
