import type { NextPage } from "next";

import Header from "components/Header";
import Screen from "components/Screen";
import Head from "next/head";
import Image from "next/image";
import Main from "components/Main";
import Footer from "components/Footer";

const SpritePlayerLarge = dynamic(
  () => import("components/SpritePlayerLarge"),
  {
    ssr: false,
  }
);

import { decodeUrlSprite, getRandomHash } from "utils/hash";
import dynamic from "next/dynamic";
import { useMemo } from "react";
import { useRouter } from "next/router";
import { Sprite, URLSprite } from "types/sprite";

const Home: NextPage = () => {
  const router = useRouter();
  const { query } = router;

  const { n, a, s, d, p, f } = query;

  const urlSprite = {
    n: n as string,
    a: a as string,
    s: parseInt(String(s)) as number,
    d: parseInt(String(d)) as number,
    p: String(p).split(","),
    f: String(f).split(","),
  } as URLSprite;

  const spriteData = decodeUrlSprite(urlSprite);

  return (
    <Screen>
      <Head>
        <title>{query.name} - Miko</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header
        action={{
          text: "My creations",
          url: "/app/my-creations",
        }}
      />

      <Main centered>
        <div
          style={{
            width: "100%",
            maxWidth: "48rem",
          }}
        >
          <SpritePlayerLarge spriteData={spriteData} />
        </div>
      </Main>

      <Footer
        shortcuts={[
          {
            children: "L",
            label: "Login",
            hotKeys: "l",
            onToggle: () => router.push("/app/login"),
          },
          {
            children: "⏎",
            label: "Draw",
            hotKeys: "enter",
            onToggle: () => router.push("/app/editor"),
          },
        ]}
        action={{ text: "Let me try!", url: "/app/editor" }}
      />
    </Screen>
  );
};

export default Home;
