import type { NextPage } from "next";

import Header from "components/Header";
import Screen from "components/Screen";
import Head from "next/head";
import Image from "next/image";
import Main from "components/Main";
import Footer from "components/Footer";

const SpritePreview = dynamic(() => import("../components/SpritePreview"), {
  ssr: false,
});

import { getRandomHash } from "utils/hash";
import dynamic from "next/dynamic";
import { useMemo } from "react";

const Home: NextPage = () => {
  const hashArray = useMemo(
    () => ({
      hash: getRandomHash(),
    }),
    []
  );

  console.log("hashArray: ", hashArray.hash);

  return (
    <Screen>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header
        action={{
          text: "What is this?",
          url: "/about",
        }}
      />

      <Main centered>
        <div
          style={{
            width: "100%",
            maxWidth: "48rem",
          }}
        >
          <SpritePreview
            hash={hashArray.hash}
            title="Random"
            author={{ id: "123", name: "Intendo87" }}
          />
        </div>
      </Main>

      <Footer
        shortcuts={[
          { key: "L", label: "Login" },
          { key: "D", label: "Draw" },
        ]}
        action={{ text: "Draw!", url: "/app/editor" }}
      />
    </Screen>
  );
};

export default Home;
