import type { NextPage } from "next";

import Header from "components/Header";
import Screen from "components/Screen";
import Head from "next/head";
import Image from "next/image";
import Main from "components/Main";
import Footer from "components/Footer";

const SpritePreview = dynamic(() => import("../components/SpritePreview"), {
  ssr: false,
});

import { getRandomHash, getRandomPalette } from "utils/hash";
import dynamic from "next/dynamic";
import { useMemo } from "react";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const router = useRouter();

  const randomSprite = useMemo(
    () => ({
      hash: getRandomHash(6),
      palette: getRandomPalette(),
    }),
    []
  );

  return (
    <Screen>
      <Head>
        <title>Miko.app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header
        action={{
          text: "My sprites",
          url: "/app/my-creations",
        }}
      />

      <Main centered>
        <div
          style={{
            width: "80%",
            maxWidth: "48rem",
          }}
        >
          <SpritePreview
            hash={randomSprite.hash}
            palette={randomSprite.palette}
            title="Random"
            author={{ id: "123", name: "Miko" }}
          />
        </div>
      </Main>

      <Footer
        shortcuts={[
          // {
          //   children: "L",
          //   label: "Login",
          //   hotKeys: "l",
          //   disabled: true,
          //   onToggle: () => router.push("/app/login"),
          // },
          {
            children: "⏎",
            label: "Draw",
            hotKeys: "enter",
            onToggle: () => router.push("/app/editor/sprite"),
          },
          // {
          //   children: "S",
          //   label: "Make spritesheet",
          //   hotKeys: "s",
          //   onToggle: () => router.push("/app/editor/sheet"),
          // },
          {
            children: "P",
            label: "Package",
            hotKeys: "p",
            onToggle: () => router.push("/app/editor/package"),
          },
        ]}
        action={{ text: "Draw!", url: "/app/editor/sprite" }}
      />
    </Screen>
  );
};

export default Home;
